Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"

  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
    v.cpus = 4
  end

  config.vm.synced_folder "../", "/home/vagrant/pi4"

  config.vm.provision "shell", path: "bootstrap.sh"
  config.vm.provision "shell", privileged: false, path: "setup-ocaml.sh"
  config.vm.provision "shell", privileged: false, path: "setup-petr4.sh"
  config.vm.provision "shell", privileged: false, path: "setup-z3.sh"
  config.vm.provision "shell", privileged: false, path: "setup-pi4.sh"
end
